title: "STRANDED"
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"

footer_content: "Documentation copyright &copy; 2023 Christian Rodriguez-Burns. Distributed under the terms of the <a href=\"https://www.gnu.org/licenses/fdl-1.3.en.html\">GNU Free Documentation License, version 1.3</a>, or any later version published by the Free Software Foundation."

exclude:
   - README.md
